# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/nido/code/vegastrike/market/Market v0.1.3"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/nido/code/vegastrike/market/Market v0.1.3"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/nido/code/vegastrike/market/Market v0.1.3/CMakeFiles" "/home/nido/code/vegastrike/market/Market v0.1.3/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/nido/code/vegastrike/market/Market v0.1.3/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named factory_main

# Build rule for target.
factory_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 factory_main
.PHONY : factory_main

# fast build rule for target.
factory_main/fast:
	$(MAKE) -f CMakeFiles/factory_main.dir/build.make CMakeFiles/factory_main.dir/build
.PHONY : factory_main/fast

#=============================================================================
# Target rules for targets named market_main

# Build rule for target.
market_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 market_main
.PHONY : market_main

# fast build rule for target.
market_main/fast:
	$(MAKE) -f CMakeFiles/market_main.dir/build.make CMakeFiles/market_main.dir/build
.PHONY : market_main/fast

#=============================================================================
# Target rules for targets named xmlfacotry_main

# Build rule for target.
xmlfacotry_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmlfacotry_main
.PHONY : xmlfacotry_main

# fast build rule for target.
xmlfacotry_main/fast:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/build
.PHONY : xmlfacotry_main/fast

factory_main.o: factory_main.cpp.o
.PHONY : factory_main.o

# target to build an object file
factory_main.cpp.o:
	$(MAKE) -f CMakeFiles/factory_main.dir/build.make CMakeFiles/factory_main.dir/factory_main.cpp.o
.PHONY : factory_main.cpp.o

factory_main.i: factory_main.cpp.i
.PHONY : factory_main.i

# target to preprocess a source file
factory_main.cpp.i:
	$(MAKE) -f CMakeFiles/factory_main.dir/build.make CMakeFiles/factory_main.dir/factory_main.cpp.i
.PHONY : factory_main.cpp.i

factory_main.s: factory_main.cpp.s
.PHONY : factory_main.s

# target to generate assembly for a file
factory_main.cpp.s:
	$(MAKE) -f CMakeFiles/factory_main.dir/build.make CMakeFiles/factory_main.dir/factory_main.cpp.s
.PHONY : factory_main.cpp.s

market_main.o: market_main.cpp.o
.PHONY : market_main.o

# target to build an object file
market_main.cpp.o:
	$(MAKE) -f CMakeFiles/market_main.dir/build.make CMakeFiles/market_main.dir/market_main.cpp.o
.PHONY : market_main.cpp.o

market_main.i: market_main.cpp.i
.PHONY : market_main.i

# target to preprocess a source file
market_main.cpp.i:
	$(MAKE) -f CMakeFiles/market_main.dir/build.make CMakeFiles/market_main.dir/market_main.cpp.i
.PHONY : market_main.cpp.i

market_main.s: market_main.cpp.s
.PHONY : market_main.s

# target to generate assembly for a file
market_main.cpp.s:
	$(MAKE) -f CMakeFiles/market_main.dir/build.make CMakeFiles/market_main.dir/market_main.cpp.s
.PHONY : market_main.cpp.s

scew/attribute.o: scew/attribute.c.o
.PHONY : scew/attribute.o

# target to build an object file
scew/attribute.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/attribute.c.o
.PHONY : scew/attribute.c.o

scew/attribute.i: scew/attribute.c.i
.PHONY : scew/attribute.i

# target to preprocess a source file
scew/attribute.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/attribute.c.i
.PHONY : scew/attribute.c.i

scew/attribute.s: scew/attribute.c.s
.PHONY : scew/attribute.s

# target to generate assembly for a file
scew/attribute.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/attribute.c.s
.PHONY : scew/attribute.c.s

scew/element.o: scew/element.c.o
.PHONY : scew/element.o

# target to build an object file
scew/element.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/element.c.o
.PHONY : scew/element.c.o

scew/element.i: scew/element.c.i
.PHONY : scew/element.i

# target to preprocess a source file
scew/element.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/element.c.i
.PHONY : scew/element.c.i

scew/element.s: scew/element.c.s
.PHONY : scew/element.s

# target to generate assembly for a file
scew/element.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/element.c.s
.PHONY : scew/element.c.s

scew/error.o: scew/error.c.o
.PHONY : scew/error.o

# target to build an object file
scew/error.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/error.c.o
.PHONY : scew/error.c.o

scew/error.i: scew/error.c.i
.PHONY : scew/error.i

# target to preprocess a source file
scew/error.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/error.c.i
.PHONY : scew/error.c.i

scew/error.s: scew/error.c.s
.PHONY : scew/error.s

# target to generate assembly for a file
scew/error.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/error.c.s
.PHONY : scew/error.c.s

scew/parser.o: scew/parser.c.o
.PHONY : scew/parser.o

# target to build an object file
scew/parser.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/parser.c.o
.PHONY : scew/parser.c.o

scew/parser.i: scew/parser.c.i
.PHONY : scew/parser.i

# target to preprocess a source file
scew/parser.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/parser.c.i
.PHONY : scew/parser.c.i

scew/parser.s: scew/parser.c.s
.PHONY : scew/parser.s

# target to generate assembly for a file
scew/parser.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/parser.c.s
.PHONY : scew/parser.c.s

scew/str.o: scew/str.c.o
.PHONY : scew/str.o

# target to build an object file
scew/str.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/str.c.o
.PHONY : scew/str.c.o

scew/str.i: scew/str.c.i
.PHONY : scew/str.i

# target to preprocess a source file
scew/str.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/str.c.i
.PHONY : scew/str.c.i

scew/str.s: scew/str.c.s
.PHONY : scew/str.s

# target to generate assembly for a file
scew/str.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/str.c.s
.PHONY : scew/str.c.s

scew/tree.o: scew/tree.c.o
.PHONY : scew/tree.o

# target to build an object file
scew/tree.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/tree.c.o
.PHONY : scew/tree.c.o

scew/tree.i: scew/tree.c.i
.PHONY : scew/tree.i

# target to preprocess a source file
scew/tree.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/tree.c.i
.PHONY : scew/tree.c.i

scew/tree.s: scew/tree.c.s
.PHONY : scew/tree.s

# target to generate assembly for a file
scew/tree.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/tree.c.s
.PHONY : scew/tree.c.s

scew/writer.o: scew/writer.c.o
.PHONY : scew/writer.o

# target to build an object file
scew/writer.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/writer.c.o
.PHONY : scew/writer.c.o

scew/writer.i: scew/writer.c.i
.PHONY : scew/writer.i

# target to preprocess a source file
scew/writer.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/writer.c.i
.PHONY : scew/writer.c.i

scew/writer.s: scew/writer.c.s
.PHONY : scew/writer.s

# target to generate assembly for a file
scew/writer.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/writer.c.s
.PHONY : scew/writer.c.s

scew/xattribute.o: scew/xattribute.c.o
.PHONY : scew/xattribute.o

# target to build an object file
scew/xattribute.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xattribute.c.o
.PHONY : scew/xattribute.c.o

scew/xattribute.i: scew/xattribute.c.i
.PHONY : scew/xattribute.i

# target to preprocess a source file
scew/xattribute.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xattribute.c.i
.PHONY : scew/xattribute.c.i

scew/xattribute.s: scew/xattribute.c.s
.PHONY : scew/xattribute.s

# target to generate assembly for a file
scew/xattribute.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xattribute.c.s
.PHONY : scew/xattribute.c.s

scew/xerror.o: scew/xerror.c.o
.PHONY : scew/xerror.o

# target to build an object file
scew/xerror.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xerror.c.o
.PHONY : scew/xerror.c.o

scew/xerror.i: scew/xerror.c.i
.PHONY : scew/xerror.i

# target to preprocess a source file
scew/xerror.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xerror.c.i
.PHONY : scew/xerror.c.i

scew/xerror.s: scew/xerror.c.s
.PHONY : scew/xerror.s

# target to generate assembly for a file
scew/xerror.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xerror.c.s
.PHONY : scew/xerror.c.s

scew/xhandler.o: scew/xhandler.c.o
.PHONY : scew/xhandler.o

# target to build an object file
scew/xhandler.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xhandler.c.o
.PHONY : scew/xhandler.c.o

scew/xhandler.i: scew/xhandler.c.i
.PHONY : scew/xhandler.i

# target to preprocess a source file
scew/xhandler.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xhandler.c.i
.PHONY : scew/xhandler.c.i

scew/xhandler.s: scew/xhandler.c.s
.PHONY : scew/xhandler.s

# target to generate assembly for a file
scew/xhandler.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xhandler.c.s
.PHONY : scew/xhandler.c.s

scew/xparser.o: scew/xparser.c.o
.PHONY : scew/xparser.o

# target to build an object file
scew/xparser.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xparser.c.o
.PHONY : scew/xparser.c.o

scew/xparser.i: scew/xparser.c.i
.PHONY : scew/xparser.i

# target to preprocess a source file
scew/xparser.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xparser.c.i
.PHONY : scew/xparser.c.i

scew/xparser.s: scew/xparser.c.s
.PHONY : scew/xparser.s

# target to generate assembly for a file
scew/xparser.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xparser.c.s
.PHONY : scew/xparser.c.s

scew/xprint.o: scew/xprint.c.o
.PHONY : scew/xprint.o

# target to build an object file
scew/xprint.c.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xprint.c.o
.PHONY : scew/xprint.c.o

scew/xprint.i: scew/xprint.c.i
.PHONY : scew/xprint.i

# target to preprocess a source file
scew/xprint.c.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xprint.c.i
.PHONY : scew/xprint.c.i

scew/xprint.s: scew/xprint.c.s
.PHONY : scew/xprint.s

# target to generate assembly for a file
scew/xprint.c.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/scew/xprint.c.s
.PHONY : scew/xprint.c.s

xmlfactory_main.o: xmlfactory_main.cpp.o
.PHONY : xmlfactory_main.o

# target to build an object file
xmlfactory_main.cpp.o:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/xmlfactory_main.cpp.o
.PHONY : xmlfactory_main.cpp.o

xmlfactory_main.i: xmlfactory_main.cpp.i
.PHONY : xmlfactory_main.i

# target to preprocess a source file
xmlfactory_main.cpp.i:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/xmlfactory_main.cpp.i
.PHONY : xmlfactory_main.cpp.i

xmlfactory_main.s: xmlfactory_main.cpp.s
.PHONY : xmlfactory_main.s

# target to generate assembly for a file
xmlfactory_main.cpp.s:
	$(MAKE) -f CMakeFiles/xmlfacotry_main.dir/build.make CMakeFiles/xmlfacotry_main.dir/xmlfactory_main.cpp.s
.PHONY : xmlfactory_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... factory_main"
	@echo "... market_main"
	@echo "... rebuild_cache"
	@echo "... xmlfacotry_main"
	@echo "... factory_main.o"
	@echo "... factory_main.i"
	@echo "... factory_main.s"
	@echo "... market_main.o"
	@echo "... market_main.i"
	@echo "... market_main.s"
	@echo "... scew/attribute.o"
	@echo "... scew/attribute.i"
	@echo "... scew/attribute.s"
	@echo "... scew/element.o"
	@echo "... scew/element.i"
	@echo "... scew/element.s"
	@echo "... scew/error.o"
	@echo "... scew/error.i"
	@echo "... scew/error.s"
	@echo "... scew/parser.o"
	@echo "... scew/parser.i"
	@echo "... scew/parser.s"
	@echo "... scew/str.o"
	@echo "... scew/str.i"
	@echo "... scew/str.s"
	@echo "... scew/tree.o"
	@echo "... scew/tree.i"
	@echo "... scew/tree.s"
	@echo "... scew/writer.o"
	@echo "... scew/writer.i"
	@echo "... scew/writer.s"
	@echo "... scew/xattribute.o"
	@echo "... scew/xattribute.i"
	@echo "... scew/xattribute.s"
	@echo "... scew/xerror.o"
	@echo "... scew/xerror.i"
	@echo "... scew/xerror.s"
	@echo "... scew/xhandler.o"
	@echo "... scew/xhandler.i"
	@echo "... scew/xhandler.s"
	@echo "... scew/xparser.o"
	@echo "... scew/xparser.i"
	@echo "... scew/xparser.s"
	@echo "... scew/xprint.o"
	@echo "... scew/xprint.i"
	@echo "... scew/xprint.s"
	@echo "... xmlfactory_main.o"
	@echo "... xmlfactory_main.i"
	@echo "... xmlfactory_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

